### ISSUE TITLE
API throws non-descriptive error when setting an empty value

### ISSUE THREAD

**Issue by nicolasschwarz** [IPG-Automotive-UK/infofile-utils#2]
## Issue
- when using the setValue method with an emtpy value like `null`, `undefined,`""`,` `" "` etc. the API throws "no error"
- e.g. `infofile.setValue({file, values: {keys: "Test.1", value: null}});`
![grafik](https://user-images.githubusercontent.com/68536383/183008721-97565f74-2dc9-4cdd-8957-d1d5b46a514b.png)
- this becomes hard to debug when setting an array of values and one of the values is undefined
- ideally the API should either write an emtpy object in the infofile or include the key that caused the error in the error message

**Comment by dmbarry86** [comment]
@jegasriskantha please can you take a look at this.
